index:    
   path: /
   controller: App\Controller\FrontController::index

produitsparcategories:
   path: /produits-par-categories/{nomcategorie}
   controller: App\Controller\FrontController::ProduitsParCategories

produitsfiltre:
   path: /produits-par-categories-filtre/{nomcategorie}
   controller: App\Controller\FrontController::ResultatsFiltre

contact:
   path: /contact
   controller: App\Controller\FrontController::Contact

blog:
   path: /blog
   controller: App\Controller\FrontController::AffichageBlog

wishlist:
   path: /wishlist
   controller: App\Controller\FrontController::AffichageWishlist

panier:
   path: /panier
   controller: App\Controller\FrontController::AffichagePanier

checkout:
   path: /checkout
   controller: App\Controller\FrontController::AffichageCheckout

produitdetail:
   path: /produit-detail/{id}
   controller: App\Controller\FrontController::AffichageProduitDetail

postdetail:
   path: /post-detail/{id}
   controller: App\Controller\FrontController::AffichagePostDetail

   